[build]
  command = "npm run build"
  publish = "client/build"
  functions = "server"

[build.environment]
  NODE_VERSION = "14"

[dev]
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
